apiVersion: apps/v1
#Resource type
kind: Deployment
metadata:
  #Resource name
  name: client
  labels:
    #Labels for other resource to know
    app: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        #Image to use
        - image: bahachammakhi/client
          imagePullPolicy: Always
          name: client
          ports:
            #Port
            - containerPort: 80
