apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - image: bahachammakhi/server
          imagePullPolicy: Always
          name: server
          env:
            - name: DATABASE
              value: mongodb://mongo:27017/dev
            - name: DATABASE_PASSWORD
              value: ""
          ports:
            - containerPort: 3000
